name: Build
on: [push, pull_request]
jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: gradle/actions/wrapper-validation@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e
      - uses: eskatos/gradle-command-action@ac2d340dc04d9e1113182899e983b5400c17cda1
        with:
          arguments: wrapper
      - run: |
          git status --porcelain
          if [[ -n $(git status --porcelain) ]]; then 
            echo "Gradle wrapper files have not been updated."
            echo "Please run Gradle wrapper task and commit wrapper changes."
            exit 1
          fi
  gradle:
    name: "Build"
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-14, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
    - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
      with:
        java-version: 11
        distribution: zulu
    - uses: eskatos/gradle-command-action@ac2d340dc04d9e1113182899e983b5400c17cda1
      with:
        arguments: build --parallel --continue
